name: CI

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "yarn"

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run ESLint
      - name: Run ESLint
        run: yarn lint

      # Run TypeScript type check
      - name: TypeScript type check
        run: yarn tsc --noEmit

      # Run tests
      - name: Run tests
        run: yarn test

      # Build Next.js app
      - name: Build Next.js
        run: yarn build
